### Create Order
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

{
    "userId": 1,
    "orderLines": [
        {
            "productId": 2,
            "quantity": 2
        },
        {
            "productId": 3,
            "quantity": 1
        }
    ]
}

### Find All Orders
GET http://localhost:3000/orders HTTP/1.1

### Find One Order
GET http://localhost:3000/orders/3 HTTP/1.1

### Update Order
PATCH http://localhost:3000/orders/3 HTTP/1.1
Content-Type: application/json

{
    "userId": 1,
    "orderLines": [
        {
            "productId": 1,
            "quantity": 30
        }
    ]
}

### Update Order Lines
PATCH http://localhost:3000/orders/8/order-lines HTTP/1.1
Content-Type: application/json

{
    "orderLines": [
        {
            "orderLineId": null,
            "productId": 1,
            "quantity": 10
        }
    ]
}

### Delete Order
DELETE http://localhost:3000/orders/2 HTTP/1.1
